[package]
name = "instrumented-channels"
version = "0.3.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
pin-project = "1.1.8"
tokio = { version = "1.43.0", features = ["sync"] }
tracing = "0.1.41"
uuid = { version = "1.12.0", features = ["v4"] }
